language: node_js

node_js:
  - 8.0.0

yarn: true

install:
  - yarn

cache:
  directories:
    node_modules

before_script:
  - yarn server --silent &
  - yarn start --silent &

before_install:
 - cd server
 - yarn
 - cd ..
 - cd client

script:
  - yarn record

notifications:
  email: false